#!/usr/bin/env bash
set -e

if command -v python &>/dev/null; then
    python -m migrate "$@"
elif command -v python3 &>/dev/null; then
    python3 -m migrate "$@"
else
    echo "Python is not installed"
    exit 1
fi